// HTTP entrypoint: Streamable-HTTP MCP server (PRD §12). Public + unauthenticated.
// Single Cloud Run instance + session affinity, so a session never crosses instances.

import express from "express";
import rateLimit from "express-rate-limit";
import { randomUUID } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { isInitializeRequest } from "@modelcontextprotocol/sdk/types.js";
import { buildServer } from "./server.js";
import { config } from "./lib/config.js";

const app = express();
app.set("trust proxy", 1);
app.use(express.json({ limit: "256kb" }));

const mcpLimiter = rateLimit({
  windowMs: 60_000,
  max: Number(process.env.RATE_LIMIT_PER_MIN || 60),
  standardHeaders: true,
  legacyHeaders: false,
  message: { jsonrpc: "2.0", error: { code: -32000, message: "Rate limit exceeded; slow down." }, id: null },
});

// The marketing + explorable-dashboard site (cns.me design system), generated by scripts/build-site.mjs
// into ./public and baked into the image. Served at the root; the MCP stays at /mcp.
const PUBLIC_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "public");
app.get("/health", (_req, res) => res.json({ status: "ok", service: "govbuy-mcp", version: "0.1.0" }));
app.get("/", (_req, res) => res.sendFile(path.join(PUBLIC_DIR, "index.html")));
app.use(express.static(PUBLIC_DIR, { index: false, maxAge: "1h", fallthrough: true }));

const transports: Record<string, StreamableHTTPServerTransport> = {};
app.use("/mcp", mcpLimiter);

app.post("/mcp", async (req, res) => {
  try {
    const sid = req.headers["mcp-session-id"] as string | undefined;
    let transport = sid ? transports[sid] : undefined;
    if (!transport && isInitializeRequest(req.body)) {
      transport = new StreamableHTTPServerTransport({
        sessionIdGenerator: () => randomUUID(),
        onsessioninitialized: (id) => { transports[id] = transport!; },
      });
      transport.onclose = () => { if (transport!.sessionId) delete transports[transport!.sessionId]; };
      const server = buildServer();
      await server.connect(transport);
    } else if (!transport) {
      res.status(400).json({ jsonrpc: "2.0", error: { code: -32000, message: "No valid session; send an initialize request first." }, id: null });
      return;
    }
    await transport.handleRequest(req, res, req.body);
  } catch (err) {
    console.error("mcp POST error", err);
    if (!res.headersSent) res.status(500).json({ jsonrpc: "2.0", error: { code: -32603, message: "Internal error" }, id: null });
  }
});

const sessionRequest = async (req: express.Request, res: express.Response) => {
  const sid = req.headers["mcp-session-id"] as string | undefined;
  const transport = sid ? transports[sid] : undefined;
  if (!transport) { res.status(400).send("Invalid or missing session id"); return; }
  await transport.handleRequest(req, res);
};
app.get("/mcp", sessionRequest);
app.delete("/mcp", sessionRequest);

app.listen(config.port, () => {
  console.log(`govbuy-mcp MCP API on :${config.port} (project=${config.project}, dataset=${config.publicDataset})`);
});
