#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" --repo chrisns/govbuy >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name --repo chrisns/govbuy)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" --repo chrisns/govbuy >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s = %s\n' "$GREEN" "$RESET" "$name" "$value"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name (set it manually: gh variable set $name --body '$value' --repo chrisns/govbuy)")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — turn on the govbuy nightly refresh (ADR-0006, supersedes ADR-0005).
# Run this from the repo root: scripts/setup_govbuy_refresh_wizard.sh
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
GCP_PROJECT="govreposcrape"

banner "govbuy nightly refresh — one-off setup"
say "This wires up .github/workflows/govbuy-refresh.yml so govbuy-ingest refresh"
say "runs on its own every night at 03:00 UTC, keyless via Workload Identity"
say "Federation, instead of only when you run it by hand."
note "Run this from the repo root. It needs: gcloud, terraform, gh (logged in)."

# ── Stage 1: GCP auth ───────────────────────────────────────────────────
stage "GCP authentication"
say "Two separate credentials are needed: one for the gcloud/bq CLI, one for"
say "Terraform (Application Default Credentials). Skipped below if already valid."
if gcloud auth print-access-token >/dev/null 2>&1; then
  note "gcloud CLI already has a valid token — skipping login."
else
  step "gcloud CLI login (opens a browser):"
  gcloud auth login
fi
if gcloud auth application-default print-access-token >/dev/null 2>&1; then
  note "Application Default Credentials already valid — skipping login."
else
  step "Application Default Credentials for Terraform (opens a browser):"
  gcloud auth application-default login
fi
note "Neither command changes your active gcloud config (scrumpoker) — every"
note "command below passes --project=$GCP_PROJECT explicitly."

# ── Stage 2: Terraform apply — WIF pool + provider + IAM binding ─────────
stage "Terraform — Workload Identity Federation"
say "Creates: a WIF pool + GitHub OIDC provider scoped to chrisns/govbuy only,"
say "and grants it roles/iam.workloadIdentityUser on the existing govbuy-ingest"
say "service account. This is an IAM change on a shared GCP project."
say "Review terraform/main.tf before continuing if you want to see the plan."
pushd terraform >/dev/null
terraform init
export TF_VAR_project="$GCP_PROJECT"
terraform plan -out=/tmp/govbuy-wif.tfplan
if confirm "Apply this Terraform plan to $GCP_PROJECT now?"; then
  terraform apply /tmp/govbuy-wif.tfplan
else
  warn "skipped terraform apply — re-run this wizard when you're ready."
  SKIPPED+=("terraform apply (terraform/, TF_VAR_project=$GCP_PROJECT)")
  popd >/dev/null
  finish
  exit 0
fi
GOVBUY_WIF_PROVIDER_VALUE=$(terraform output -raw github_wif_provider)
GOVBUY_INGEST_SA_VALUE=$(terraform output -raw ingest_sa)
popd >/dev/null
say "Provider: $GOVBUY_WIF_PROVIDER_VALUE"
say "Ingest SA: $GOVBUY_INGEST_SA_VALUE"

# ── Stage 3: GitHub Actions repo variables ────────────────────────────────
stage "GitHub Actions — repo variables"
say "The workflow reads these as vars.GOVBUY_WIF_PROVIDER / vars.GOVBUY_INGEST_SA"
say "to authenticate. Not secret — just names."
set_var GOVBUY_WIF_PROVIDER "$GOVBUY_WIF_PROVIDER_VALUE"
set_var GOVBUY_INGEST_SA "$GOVBUY_INGEST_SA_VALUE"

# ── Stage 4: GitHub Actions repo secrets ──────────────────────────────────
stage "GitHub Actions — repo secrets"
say "The workflow needs these to run the extract/verify LLM steps and the"
say "Companies House match. COMPANIES_HOUSE_API is already in your local .env;"
say "Enter keeps it. ANTHROPIC_API_KEY isn't in .env yet — paste one from"
say "https://console.anthropic.com/settings/keys (a key scoped for this harness,"
say "not your personal one, if you keep them separate)."
ask_secret COMPANIES_HOUSE_API "Companies House API key:"
ask_secret ANTHROPIC_API_KEY "Anthropic API key for the ingest harness:"
write_env COMPANIES_HOUSE_API "$COMPANIES_HOUSE_API"
write_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"
set_secret GOVBUY_COMPANIES_HOUSE_API "$COMPANIES_HOUSE_API"
set_secret GOVBUY_ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"

# ── Stage 5: dry-run the workflow ─────────────────────────────────────────
stage "Dry run"
say "Trigger the workflow once by hand and watch it end to end (auth → refresh"
say "→ liveness) before trusting the 03:00 UTC cron."
if confirm "Trigger govbuy-refresh.yml now? (this spends real Anthropic + CH API budget)"; then
  gh workflow run govbuy-refresh.yml --repo chrisns/govbuy
  sleep 5
  RUN_ID=$(gh run list --repo chrisns/govbuy --workflow=govbuy-refresh.yml --limit 1 --json databaseId -q '.[0].databaseId')
  say "Watching run $RUN_ID (this can take a while — refresh walks the frontier)..."
  gh run watch "$RUN_ID" --repo chrisns/govbuy --exit-status || warn "the dry run failed — check: gh run view $RUN_ID --repo chrisns/govbuy --log-failed"
else
  note "skipped the dry run — trigger it later with: gh workflow run govbuy-refresh.yml --repo chrisns/govbuy"
fi

# ── Stage 6: done ──────────────────────────────────────────────────────────
stage "Done"
say "The workflow is already scheduled (03:00 UTC nightly) in"
say ".github/workflows/govbuy-refresh.yml — no further action needed once the"
say "dry run above is green."
note "A failed scheduled run is now the dead-man's-switch: it shows up as a"
note "red run in the repo's Actions tab (govbuy-ingest liveness is the last step)."
# ──────────────────────────────────────────────────────────────────────────

finish
